---
layout: cv
title: Mosiah Valdez-Bates Résumé
---
# Mosiah Valdez-Bates
software engineer, Web developer

<div id="webaddress">
<a href="mosiahvaldezbates@gmail.com">mosiahvaldezbates@gmail.com</a>
| <a href="http://www.linkedin.com/in/mosiahvaldez-84588a1a5">My Linked in profile page</a>
</div>

## Introductory Summary
Enthusiastic learner dedicated to understanding team dynamics and individual needs. Always ensuring effective collaboration to achieve targets, milestones, and exceed expectations. Highly experienced in fostering positive interpersonal relationships and consistently delivering positive outcomes for all stakeholders. Proactively learns from challenges to contribute to the development of high-functioning software projects.

## Education
**Brigham Young University-Idaho**  
Bachelor of Science in Software Engineering, December 2024  
Rexburg, ID  

Relevant Classes:
- Programming Building Blocks
- Programming with Functions
- Programming with Classes
- Programming with Data Structures
- Applied Programming
- Software Testing
- JavaScript Language
- Web Fundamentals
- IT Management and Dev-Ops
- Networking

## Skills
Worked with:
- Python
- HTML, CSS, JavaScript
- Strong analytical skills and attention to detail

## Work Experience

### Pro Moto Billet
*AP Clerk*, September 2022 – Present  
Nampa, ID  
- Managed end-to-end invoicing and purchasing processes with vendors, ensuring accuracy and timeliness. Coordinated and executed office projects utilizing Excel sheets for data analysis and reporting.
- Operated and maintained CNC machines, overseeing entire machining process ensuring precision and quality in production of physical products demonstrating a keen eye for detail and adherence to quality standards.

### Rove Pest Control
*Technician*, April 2020 – August 2022  
Boston, MA  
- Orchestrated a significant boost in online reputation by cultivating over 200 5-star reviews, elevating four underperforming locations from low-ranking reviews to succeeding 4.7 stars or higher.
- Led a team of eight in developing effective customer interaction and communication strategies, fostering positive service experiences, and generating customer referrals for new business opportunities.

### Rove Pest Control - Internship
*Team Lead of Sales*, April 2021 – August 2021  
Boston, MA  
- Spearheaded a dynamic team of first-year door-to-door sales representatives during a summer internship. Achieved and exceeded given targets, generating over half a million dollars in revenue through cold calling in a span of 4 months.
- Demonstrated strong leadership skills by developing Rove's most profitable sales team, by focusing on understanding all 10 team members needs and wants to maintain morale and prepare effective training programs.